"""empty message

Revision ID: 0907621acc9f
Revises: 7f95adbe7153
Create Date: 2022-12-27 05:56:05.715380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0907621acc9f'
down_revision = '7f95adbe7153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
