"""empty message

Revision ID: bab94f360636
Revises: d862c3b0297e
Create Date: 2022-12-27 05:57:42.070529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab94f360636'
down_revision = 'd862c3b0297e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registeruser',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='registeruser_pkey')
    )
    op.create_index('ix_registeruser_id', 'registeruser', ['id'], unique=False)
    op.create_index('ix_registeruser_email', 'registeruser', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_registeruser_email', table_name='registeruser')
    op.drop_index('ix_registeruser_id', table_name='registeruser')
    op.drop_table('registeruser')
    # ### end Alembic commands ###
