"""empty message

Revision ID: d862c3b0297e
Revises: 0907621acc9f
Create Date: 2022-12-27 05:56:36.906405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd862c3b0297e'
down_revision = '0907621acc9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
